#!/usr/bin/env node
/**
 * TRIOS Token Build Pipeline
 * Input:  tokens/trios.tokens.json
 * Output:
 *   generated/trios_tokens.h     → Chromium C++ header
 *   generated/trios_tokens.css    → Extension CSS variables
 *
 * No external dependencies — pure Node.js.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const TOKENS_PATH = resolve(__dirname, 'trios.tokens.json')
const GENERATED_DIR = resolve(ROOT, 'chromium_patches/chrome/browser/browseros/generated')

// ── Helpers ──────────────────────────────────────────────

function hexToSkColor(hex) {
  const h = hex.replace('#', '')
  const r = parseInt(h.slice(0, 2), 16)
  const g = parseInt(h.slice(2, 4), 16)
  const b = parseInt(h.slice(4, 6), 16)
  return `0xFF${h.toUpperCase()}`
}

const OKLCH_TABLE = {
  '#000000': 'oklch(0 0 0)',
  '#0A0A0A': 'oklch(0.04 0 0)',
  '#141414': 'oklch(0.08 0 0)',
  '#1F1F1F': 'oklch(0.12 0 0)',
  '#2A2A2A': 'oklch(0.17 0 0)',
  '#353535': 'oklch(0.22 0 0)',
  '#6A6A6A': 'oklch(0.44 0 0)',
  '#9A9A9A': 'oklch(0.63 0 0)',
  '#E5E5E5': 'oklch(0.91 0 0)',
  '#FFFFFF': 'oklch(1 0 0)',
  '#D1AD72': 'oklch(0.766 0.087 79.2)',
  '#E6C491': 'oklch(0.828 0.078 79.2)',
  '#B8955A': 'oklch(0.694 0.096 79.2)',
  '#E74C3C': 'oklch(0.577 0.245 27.3)',
  '#27AE60': 'oklch(0.648 0.156 149.0)',
  '#F39C12': 'oklch(0.738 0.158 71.0)',
}

function hexToOklch(hex) {
  return OKLCH_TABLE[hex.toUpperCase()] || `/* unknown: ${hex} */`
}

// ── Resolve references ───────────────────────────────────

function resolveValue(raw, allColors) {
  if (!raw.startsWith('{')) return raw
  // {color.black.0} → #000000
  const ref = raw.slice(1, -1) // strip { }
  const parts = ref.split('.')
  let node = allColors
  for (const p of parts) {
    node = node?.[p]
  }
  return node?.$value || raw
}

// ── Parse tokens ─────────────────────────────────────────

function parseTokens(json) {
  const colors = {}  // flat: "color.black.0" → "#000000"
  const darkTokens = {}  // "theme.dark.background" → "#000000"
  const chromiumTokens = {}  // "theme.chromium.colorScheme" → "dark"

  // Flatten color.* tokens
  for (const [k1, v1] of Object.entries(json.color || {})) {
    for (const [k2, v2] of Object.entries(v1)) {
      if (v2.$value) {
        colors[`color.${k1}.${k2}`] = v2.$value
      }
    }
  }

  // Resolve theme.dark.* references
  for (const [k, v] of Object.entries(json.theme?.dark || {})) {
    if (v.$value) {
      darkTokens[`theme.dark.${k}`] = resolveValue(v.$value, json)
    }
  }

  // Resolve theme.chromium.* values
  for (const [k, v] of Object.entries(json.theme?.chromium || {})) {
    if (v.$value) {
      chromiumTokens[`theme.chromium.${k}`] = resolveValue(v.$value, json)
    }
  }

  return { colors, darkTokens, chromiumTokens }
}

// ── Generate C++ header ──────────────────────────────────

function generateCppHeader({ colors, darkTokens, chromiumTokens }) {
  const constEntries = []

  // Primitive color tokens
  for (const [key, hex] of Object.entries(colors)) {
    const name = 'k' + key.split('.').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('')
    const sk = hexToSkColor(hex)
    constEntries.push(`constexpr SkColor ${name} = ${sk};  // ${hex}`)
  }

  // Semantic dark tokens
  constEntries.push('')
  constEntries.push('// Semantic colors — dark theme')
  for (const [key, hex] of Object.entries(darkTokens)) {
    const name = 'k' + key.split('.').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('')
    const sk = hexToSkColor(hex)
    constEntries.push(`constexpr SkColor ${name} = ${sk};  // ${hex}`)
  }

  // Chromium defaults
  constEntries.push('')
  constEntries.push('// Chromium theme defaults')
  constEntries.push('constexpr int kDefaultColorScheme = 2;  // BrowserColorScheme::kDark')
  constEntries.push('constexpr SkColor kFrameSeedColor = kColorBlack0;  // #000000 TOTAL BLACK')

  return `// AUTO-GENERATED by packages/browseros/tokens/build.mjs
// DO NOT EDIT MANUALLY — edit tokens/trios.tokens.json instead
// Run: bun run tokens:build

#ifndef CHROME_BROWSER_BROWSEROS_GENERATED_TRIOS_TOKENS_H_
#define CHROME_BROWSER_BROWSEROS_GENERATED_TRIOS_TOKENS_H_

#include "third_party/skia/include/core/SkColor.h"

namespace trios {

${constEntries.join('\n')}

}  // namespace trios

#endif  // CHROME_BROWSER_BROWSEROS_GENERATED_TRIOS_TOKENS_H_
`
}

// ── Generate CSS ─────────────────────────────────────────

function generateCss({ darkTokens }) {
  const vars = []
  for (const [key, hex] of Object.entries(darkTokens)) {
    const prop = '--' + key.split('.').slice(2).join('-')
    const val = hexToOklch(hex)
    vars.push(`  ${prop}: ${val};`)
  }

  return `/* AUTO-GENERATED by packages/browseros/tokens/build.mjs */
/* DO NOT EDIT MANUALLY — edit tokens/trios.tokens.json instead */
/* Run: bun run tokens:build */

:root,
.dark {
${vars.join('\n')}
}
`
}

// ── Main ─────────────────────────────────────────────────

function main() {
  console.log('🔧 TRIOS Token Build Pipeline')
  console.log(`   Input: ${TOKENS_PATH}`)

  const raw = JSON.parse(readFileSync(TOKENS_PATH, 'utf-8'))
  const parsed = parseTokens(raw)

  mkdirSync(GENERATED_DIR, { recursive: true })

  // Generate C++ header
  const hPath = resolve(GENERATED_DIR, 'trios_tokens.h')
  const hContent = generateCppHeader(parsed)
  writeFileSync(hPath, hContent)
  console.log(`   ✓ → ${hPath}`)

  // Generate CSS
  const cssPath = resolve(GENERATED_DIR, 'trios_tokens.css')
  const cssContent = generateCss(parsed)
  writeFileSync(cssPath, cssContent)
  console.log(`   ✓ → ${cssPath}`)

  console.log('✅ TRIOS tokens built successfully')
  console.log('   Next: bun run tokens:apply  (runtime, no rebuild)')
  console.log('   Then: cd packages/browseros && ./build.sh  (full rebuild)')
}

main()
