/**
 * @license
 * Copyright 2025 BrowserOS
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
import { HttpAgentError } from '../errors'

export class PortableAgentError extends HttpAgentError {
  constructor(
    message: string,
    public code: ErrorCode,
    public agentName?: string,
  ) {
    super(message)
    this.name = 'PortableAgentError'
  }
}

export enum ErrorCode {
  CONFIG_NOT_FOUND = 'CONFIG_NOT_FOUND',
  CONFIG_INVALID = 'CONFIG_INVALID',
  CONFIG_SCHEMA_ERROR = 'CONFIG_SCHEMA_ERROR',
  CONFIG_PARSE_ERROR = 'CONFIG_PARSE_ERROR',
  ENV_VAR_NOT_FOUND = 'ENV_VAR_NOT_FOUND',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  TEMPLATE_INVALID = 'TEMPLATE_INVALID',
  TEMPLATE_LOAD_FAILED = 'TEMPLATE_LOAD_FAILED',
  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  AGENT_ALREADY_RUNNING = 'AGENT_ALREADY_RUNNING',
  AGENT_START_FAILED = 'AGENT_START_FAILED',
  AGENT_STOP_FAILED = 'AGENT_STOP_FAILED',
  AGENT_DISPOSE_FAILED = 'AGENT_DISPOSE_FAILED',
  TASK_REJECTED = 'TASK_REJECTED',
  TASK_TIMEOUT = 'TASK_TIMEOUT',
  TASK_ABORTED = 'TASK_ABORTED',
  RESOURCE_LIMIT_EXCEEDED = 'RESOURCE_LIMIT_EXCEEDED',
  WORKSPACE_ACCESS_DENIED = 'WORKSPACE_ACCESS_DENIED',
  LOG_READ_ERROR = 'LOG_READ_ERROR',
  TASK_SEND_FAILED = 'TASK_SEND_FAILED',
}

export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  CONFIG_NOT_FOUND: 404,
  CONFIG_INVALID: 400,
  CONFIG_SCHEMA_ERROR: 400,
  CONFIG_PARSE_ERROR: 400,
  ENV_VAR_NOT_FOUND: 400,
  TEMPLATE_NOT_FOUND: 404,
  TEMPLATE_INVALID: 400,
  TEMPLATE_LOAD_FAILED: 500,
  AGENT_NOT_FOUND: 404,
  AGENT_ALREADY_RUNNING: 409,
  AGENT_START_FAILED: 500,
  AGENT_STOP_FAILED: 500,
  AGENT_DISPOSE_FAILED: 500,
  TASK_REJECTED: 503,
  TASK_TIMEOUT: 408,
  TASK_ABORTED: 408,
  RESOURCE_LIMIT_EXCEEDED: 429,
  WORKSPACE_ACCESS_DENIED: 403,
  LOG_READ_ERROR: 500,
  TASK_SEND_FAILED: 500,
}

export function getStatusCodeForError(code: ErrorCode): number {
  return ERROR_STATUS_MAP[code] || 500
}
